namespace BinarySerializer.Klonoa.DTP
{
    public enum GlobalModifierType
    {
        Unknown,
        WindSwirl,
        BigWindmill,
        SmallWindmill,
        MovingPlatform,
        RoadSign,
        TiltRock,
        Minecart,
        RongoLango,
        Bell,
        LockedDoor_0,
        LockedDoor_1,
        LockedDoor_2,
        WaterWheel,
        Crate,
        MultiWheel,
        Gondola,
        FallingTreePart,
        WoodenCart,
        WoodenMallet,
        VerticallyMovingWoodenPlatform,
        Cogwheel,
        SpinningWood,
        SpinningWoodAttachedPlatform,
        MovingLedge,
        Ledge,
        UnstablePlatform,
        SwingingPlatform,
        Light,
        GeyserPlatform,
        ScrollAnimation, // Scrolls the UVs for the level model
        VRAMScrollAnimation, // Scrolls regions in VRAM
        Object,
        LevelModelSection,
        ScenerySprites,
        TextureAnimation,
        PaletteAnimation,
        Special,
        WeatherEffect,
    }
}